Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [7]:
a =  np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.


In [8]:
# 1. Форма (3, 4)
b1 = a.reshape((3, 4))

# 2. Форма (2, 6)
b2 = a.reshape((2, 6))

# 3. Форма (4, 3)
b3 = a.reshape((4, 3))

# 4. Форма (6, 2)
b4 = a.reshape((6, 2))

# 5. Форма (12, 1)
b5 = a.reshape((12, 1))
print("Массив a:", a)
print("Массив b1 (3, 4):\n", b1)
print("Массив b2 (2, 6):\n", b2)
print("Массив b3 (4, 3):\n", b3)
print("Массив b4 (6, 2):\n", b4)
print("Массив b5 (12, 1):\n", b5)


Массив a: [12 13 14 15 16 17 18 19 20 21 22 23]
Массив b1 (3, 4):
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Массив b2 (2, 6):
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Массив b3 (4, 3):
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Массив b4 (6, 2):
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Массив b5 (12, 1):
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


 Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
    нет

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,
равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.


In [9]:
# Создание массива 3x4 с случайными числами из нормального распределения
arr_2d = np.random.randn(3, 4)  # среднее 0, стандартное отклонение 1.0
arr_2d

array([[-0.80042897,  0.5760495 ,  0.52687275, -1.47684458],
       [ 0.75803372,  1.04369768,  0.18662186, -1.04475332],
       [ 0.08495815,  0.59838161, -1.13439841, -0.3354854 ]])

In [14]:
# Преобразование в одномерный массив с таким же количеством элементов
arr_1d = arr_2d.flatten()


Размер двумерного массива: (3, 4)
Размер одномерного массива: (12,)
Двумерный массив:
 [[ 0.62355828 -0.29624192 -0.88442818 -1.6875306 ]
 [ 0.33849204 -0.05110389 -1.63840502 -1.43477459]
 [ 0.13830966 -0.90243901 -2.49503048 -0.17280513]]
Одномерный массив:
 [ 0.62355828 -0.29624192 -0.88442818 -1.6875306   0.33849204 -0.05110389
 -1.63840502 -1.43477459  0.13830966 -0.90243901 -2.49503048 -0.17280513]


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с
интервалом 2.


In [10]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1
невключительно с интервалом 2. В чем разница между массивами a и b?
- Массив `a`:  
    - Размерность: Одномерный (1 ось).
    - Форма: (10,) - 10 элементов в одной строке.
    - Данные:  [20 18 16 14 12 10  8  6  4  2] 

- Массив `b`:
    - Размерность: Двумерный (2 оси).
    - Форма: (1, 10) - 1 строка, 10 столбцов.
    - Данные:  [[20 18 16 14 12 10  8  6  4  2]] 


In [11]:
b = np.arange(20, 1, -2).reshape(1, 10)

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.


In [12]:
# Вертикально соединяем массивы
# Вертикальное соединение a и b
v = np.concatenate((a.reshape(1, -1), b), axis=0)

v

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2],
       [20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),состоящая из 4 строк и 3 столбцов
Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Получится ли вычислить обратную матрицу для матрицы B 




In [13]:
a = np.arange(12)
A = a.reshape(4, 3)  # Преобразуем его в матрицу 4x3
print(A)
At = A.T  # Транспонируем матрицу A
print(At)
B = np.dot(A, At)  # Матричное умножение A на At
print(B)
determinant = np.linalg.det(B)
print(determinant) # так как равно 0 но не получ обратная матрица


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
0.0


In [14]:
# Инициализация генератора случайных чисел с seed = 42
np.random.seed(42)

# Теперь вы можете использовать np.random для генерации случайных чисел
random_numbers = np.random.rand(5)  # 5 случайных чисел от 0 до 1

print(random_numbers)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


Создайте одномерный массив c, составленный из последовательности 16-ти случайных
равномерно распределенных целых чисел от 0 до 16 невключительно.

In [15]:
c = np.random.randint(0, 16, size=16)
c

array([ 2,  6, 10, 10,  7,  4,  3,  7,  7,  2,  5,  4,  1,  7, 11, 13])

In [16]:
# Преобразуем c в квадратную матрицу C
C = c.reshape((4, 4))  # 4 строки, 4 столбца
C

array([[ 2,  6, 10, 10],
       [ 7,  4,  3,  7],
       [ 7,  2,  5,  4],
       [ 1,  7, 11, 13]])

Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.

In [17]:
# Поэлементно умножаем C на 10
C_multiplied = C * 10
# Поэлементно складываем C_multiplied и B
D = C_multiplied + B
D

array([[ 25,  74, 123, 132],
       [ 84,  90, 116, 192],
       [ 93, 106, 199, 252],
       [ 42, 192, 322, 432]])

Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [18]:
# Вычисление определителя
determinant = np.linalg.det(D)
# Вычисление ранга
rank = np.linalg.matrix_rank(D)
# Вычисление обратной матрицы
D_inv = np.linalg.inv(D)
print(f"Определитель матрицы D: {determinant}")
print(f"Ранг матрицы D: {rank}")
print(f"Обратная матрица D_inv:\n{D_inv}")

Определитель матрицы D: -25281600.000000034
Ранг матрицы D: 4
Обратная матрица D_inv:
[[ 0.00188912  0.00544902  0.00906588 -0.00828745]
 [ 0.04419973  0.02648567 -0.03311183 -0.00596165]
 [ 0.01216062 -0.01919499  0.01614771 -0.00460414]
 [-0.02889216  0.0020062   0.00179894  0.00920195]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.


In [19]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv_int = np.round(D_inv).astype(int)  # Обновляем D_inv_int после изменения D_inv
D_inv_int

array([[1, 1, 1, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 1, 1, 1]])

Убедитесь, что в матрице D_inv остались только нули и единицы

In [20]:
# Проверка с помощью модуля
if np.all(np.mod(D_inv_int, 2) == 0):  # Проверяем, что остаток от деления на 2 равен 0 для всех элементов
    print("В матрице D_inv остались только нули и единицы.")
else:
    print("В матрице D_inv есть значения, отличные от нуля и единицы.")


В матрице D_inv есть значения, отличные от нуля и единицы.


С помощью функции
numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 0, должны быть равны соответствующему элементу матрицы C

In [21]:
# Используем np.where для создания матрицы E
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23,  10],
       [ 14,  50,   3,   7],
       [ 23,   2, 149,   4],
       [  1, 122, 212, 302]])