Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a =  np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.


In [6]:
# 1. Форма (3, 4)
b1 = a.reshape((3, 4))

# 2. Форма (2, 6)
b2 = a.reshape((2, 6))

# 3. Форма (4, 3)
b3 = a.reshape((4, 3))

# 4. Форма (6, 2)
b4 = a.reshape((6, 2))

# 5. Форма (12, 1)
b5 = a.reshape((12, 1))
print("Массив a:", a)
print("Массив b1 (3, 4):\n", b1)
print("Массив b2 (2, 6):\n", b2)
print("Массив b3 (4, 3):\n", b3)
print("Массив b4 (6, 2):\n", b4)
print("Массив b5 (12, 1):\n", b5)


Массив a: [12 13 14 15 16 17 18 19 20 21 22 23]
Массив b1 (3, 4):
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Массив b2 (2, 6):
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Массив b3 (4, 3):
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Массив b4 (6, 2):
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Массив b5 (12, 1):
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


 Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
    нет

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,
равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.


In [12]:
# Создание массива 3x4 с случайными числами из нормального распределения
arr_2d = np.random.randn(3, 4)  # среднее 0, стандартное отклонение 1.0
arr_2d

array([[ 0.62355828, -0.29624192, -0.88442818, -1.6875306 ],
       [ 0.33849204, -0.05110389, -1.63840502, -1.43477459],
       [ 0.13830966, -0.90243901, -2.49503048, -0.17280513]])

In [14]:
# Преобразование в одномерный массив с таким же количеством элементов
arr_1d = arr_2d.flatten()


Размер двумерного массива: (3, 4)
Размер одномерного массива: (12,)
Двумерный массив:
 [[ 0.62355828 -0.29624192 -0.88442818 -1.6875306 ]
 [ 0.33849204 -0.05110389 -1.63840502 -1.43477459]
 [ 0.13830966 -0.90243901 -2.49503048 -0.17280513]]
Одномерный массив:
 [ 0.62355828 -0.29624192 -0.88442818 -1.6875306   0.33849204 -0.05110389
 -1.63840502 -1.43477459  0.13830966 -0.90243901 -2.49503048 -0.17280513]


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с
интервалом 2.


In [15]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1
невключительно с интервалом 2. В чем разница между массивами a и b?
- Массив `a`:  
    - Размерность: Одномерный (1 ось).
    - Форма: (10,) - 10 элементов в одной строке.
    - Данные:  [20 18 16 14 12 10  8  6  4  2] 

- Массив `b`:
    - Размерность: Двумерный (2 оси).
    - Форма: (1, 10) - 1 строка, 10 столбцов.
    - Данные:  [[20 18 16 14 12 10  8  6  4  2]] 


In [19]:
b = np.arange(20, 1, -2).reshape(1, 10)

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.


In [22]:
# Вертикально соединяем массивы
# Вертикальное соединение a и b
v = np.concatenate((a.reshape(1, -1), b), axis=0)

v

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2],
       [20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])